
modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="solplus" #mandatory

version="1.15.2-1.0.0" #mandatory

displayName="Solstica Plus" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Java and random people" #optional

authors="Me, ThunderVolt22" #optional

description='''
This mod includes a new ingot called solstica. New ores and mobs dropping this ingot are present. New items can be created!!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
